name: FireChat
description: FireChat IOS and Android Develop by QueryPeople.


publish_to: 'QueryPeople'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  flutter_platform_widgets: ^2.0.0
  equatable: ^2.0.3
  firebase_core: ^1.19.1
  firebase_auth: ^3.4.1
  permission_handler: ^10.0.0
  shared_preferences: ^2.0.15
  lottie: ^1.3.0
  theme_provider: ^0.5.0
  google_fonts: ^3.0.1
  sizer: ^2.0.15
  hexcolor: ^2.0.7
  loading_overlay: ^0.3.0
  flutter_otp_text_field: ^1.0.1
  pinput: ^2.2.11
  fluttertoast: ^8.0.9
  cloud_firestore: ^3.2.1
  firebase_storage: ^10.3.1
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  flutter_advanced_segment: ^3.0.1

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^0.1.3


flutter:


  uses-material-design: true


  assets:
    - assets/animation/





  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

